name: OA source validator

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the external repository
        uses: actions/checkout@v4
        with:
          repository: openaddresses/openaddresses
          path: oa_repo

      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run the Python script
        run: |
          python src/main.py

      - name: Wait for logs to flush
        run: sleep 2    

      - name: Display log file contents
        run: |
          echo "Log file content:"
          cat logs/url_check.log  

      - run: pwd
      - run: ls -la logs
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: logs/*
