name: OA source validator

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout the external repository
        uses: actions/checkout@v4
        with:
          repository: openaddresses/openaddresses
          path: oa_repo

      - name: List contents of external_repo
        run: |
          ls -al oa_repo

      - name: Move external repo contents
        run: |
          shopt -s dotglob  
          mv oa_repo/* .
          mv oa_repo/.[!.]* .
          rm -rf oa_repo  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run the Python script
        run: |
          python src/main.py 

      - name: Display log file contents
        run: |
          ls -a
          echo "Log file content:"
          cat out/broken_links.log  

      - run: pwd
      - run: ls -la out
      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: out/*
