name: OA source validator

on:
  workflow_dispatch:
    inputs:
      root_directory:
        description: 'Directory to process. Example: ./openaddresses/sources/us/va/'
        required: true
        default: './test'  # Default directory
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout the external repository
        uses: actions/checkout@v4
        with:
          repository: openaddresses/openaddresses
          path: openaddresses

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run the Python script
        env:
          ROOT_DIRECTORY: ${{ github.event.inputs.root_directory }}
        run: |
          python src/main.py 

      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: out/*
      
      - name: Upload badges as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: badges
          path: ./badges/

      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push badges to gh-pages branch
        run: |
          git checkout -B gh-pages
          mv ./badges/* .
          git add .
          git commit -m "Update badges"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
